### ISSUE TITLE
amp-list / bind issue with optimizer

### ISSUE THREAD

**Issue by bjalford** [ampproject/amp-toolbox#51] opened 2018-06-11 15:29 UTC
We're seeing an issue with the bind 'on' being removed front end on the optimised version. The issue occurs inside amp-list on the optimised version. The lightbox works on the valid amp version

How to replicate: Scroll to comments section at bottom of articles and click 'reply' on a comment

Note some AMP bind items work e.g. the 'Subscribe' link will launch the lightbox.

AMP version: <a class="reply-link" on="tap:reply-lightbox, AMP.setState({commentId:'1be4df17d16342659743318fb8590aff', replyTo:'tilo'})">Reply</a>

Inspect element on optimised version: <a class="reply-link">Reply</a>

Optimised amp: https://www.independent.co.uk/news/world/asia/trump-kim-meeting-live-updates-latest-time-date-location-stream-a8392686.html

Valid amp: https://www.independent.co.uk/news/world/asia/trump-kim-meeting-live-updates-latest-time-date-location-stream-a8392686.html?amp

**Comment by sebastianbenz** [comment] 2018-06-11 16:44
This sounds like: https://github.com/ampproject/amphtml/issues/15834. Did you enable the DevChannel when calculating the runtime version? 

I don't think that this is an issue with AMP Optimizer, as the `on` attribute is still present in the template markup produced by the optimizer - the rest happens at runtime.

**Comment by bjalford** [comment] 2018-06-11 18:34
Thanks - agree that seems the likely cause.

No, we're using current version code below which generates this: https://cdn.ampproject.org/rtv/001528391646530/v0/amp-live-list-0.1.js

```
const AmpOptimizerMiddleware = require('amp-toolbox-optimizer-express');
const runtimeVersion = require('amp-toolbox-runtime-version');

const { corsEnabledUrl } = require('../config');

module.exports = function () {
  const optimiser = AmpOptimizerMiddleware.create({
    runtimeVersion: () => runtimeVersion.currentVersion()
  });

  return (req, res, next) => {
    const matched = corsEnabledUrl
      .concat(['/pwamp-preview'])
      .filter((path) => req.url.startsWith(path));

    if (matched.length > 0) {
      next();
      return;
    }
    optimiser(req, res, next)
  }
};
```

**Comment by sebastianbenz** [comment] 2018-06-12 15:19
Closing this for now. Feel free to reopen in case it turns out that it's caused by Optimizer.

**Closed by sebastianbenz** 2018-06-12 15:19 UTC
