### ISSUE TITLE
specify which component versions to use

### ISSUE THREAD

**Issue by jwinkworth** [ampproject/amp-toolbox#957] opened 2020-11-25 20:05 UTC
We are writing pages using the [0.1 version of amp-carousel](https://amp.dev/documentation/components/amp-carousel-v0.1/?format=websites), but when running optimzer to generate &lt;script/&gt; tags automatically, the 0.2 url for amp-carousel is always injected.

Is there a way to specify which library versions to include?

`<script async src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js" custom-element="amp-carousel"></script>`
instead of 
`<script async src="https://cdn.ampproject.org/v0/amp-carousel-0.2.js" custom-element="amp-carousel"></script>`

Edit: I've stumbled upon the extensionVersions property, but it doesnt seem to work. My config is:
```
{
            verbose: true,
            extensionVersions: {
                "amp-carousel": "0.1"
            },
            transformations: [
                'AddMandatoryTags',
                'AutoExtensionImporter',
                'OptimizeImages',
                //'PreloadHeroImage',
                'ReorderHeadTransformer',
                'RewriteAmpUrls',
                'GoogleFontsPreconnect',
                'PruneDuplicateResourceHints',
                'SeparateKeyframes',
                'RemoveCspNonce',
                'MinifyHtml'
            ],
            minify: false
}
```

**Comment by jakobkohl** [comment] 2020-12-02 11:40
Same problem here!

I am using 
`extensionVersions: {
    'amp-experiment': '0.1',
  },`
but AmpOptimizer keeps including `amp-experiment-1.0`

**Comment by sebastianbenz** [comment] 2020-12-02 21:52
Looks like a regression, will investigate.

**Comment by sebastianbenz** [comment] 2020-12-03 15:07
I can't reproduce this. The following snippet correctly uses a custom version:

```
const AmpOptimizer = require('@ampproject/toolbox-optimizer');
const config = {
  extensionVersions: {
    //'amp-sticky-ad': '0.1',
  },
};

const optimizer = AmpOptimizer.create(config);

const input = `
<amp-sticky-ad layout="nodisplay">
  <amp-ad
    width="320"
    height="50"
    type="doubleclick"
    data-slot="/35096353/amptesting/formats/sticky"
  >
  </amp-ad>
</amp-sticky-ad>
`;

optimizer.transformHtml(input).then(html => console.log(html));
```

**Comment by jakobkohl** [comment] 2020-12-03 15:17
Thanks for the snippet. I just tried it but it is not working correctly for me: `amp-sticky-ad-1.0.js` is always included no matter what version is configured in `extensionVersions`.
I am using `"@ampproject/toolbox-optimizer": "^2.6.0"`.

**Comment by jakobkohl** [comment] 2020-12-03 15:30
Ah, now I see. `extensionVersion` is a feature of AmpOptimizer >= 2.7, right? 
I was using version 2.6.0 as it is tagged as "Latest version", but was following your docs, which are already written for version >= 2.7.0.

**Comment by sebastianbenz** [comment] 2020-12-03 20:45
That might've been the problem. Closing the issue for now. Please reopen if you encounter any problems.

**Closed by sebastianbenz** 2020-12-03 20:45 UTC
Labels: bug, toolbox-optimizer

**Comment by jwinkworth** [comment] 2020-12-07 13:45
FYI I was using it against 2.7.1-alpha, and it did not seem to work, but over the weekend I noticed a stable 2.7.1 release was available, and extensionVersions seems to work correctly for me now.

Thanks!

**Comment by sebastianbenz** [comment] 2020-12-07 14:02
Thanks for checking!
